services:
  - type: web
    name: leafdoc
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false # Set this to your Neon.tech connection string
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: AUTH_SECRET
        generateValue: true
      - key: AUTH_GOOGLE_ID
        sync: false
      - key: AUTH_GOOGLE_SECRET
        sync: false
      - key: NEXTAUTH_URL
        value: https://leafdoc.onrender.com # Update with your actual Render URL
